// client/src/themes/default/components/MaterialsSelector/components/List/Quantity/index.tsx
import { defineComponent } from '@vue/composition-api';
import debounce from 'lodash/debounce';
import { DEBOUNCE_WAIT } from '@/globals/constants';
import QuantityInput from '@/themes/default/components/QuantityInput';

import type { PropType } from '@vue/composition-api';
import type { MaterialWithAvailabilities as Material } from '@/stores/api/materials';

type Props = {
    /** Le matériel dont on veut définir les quantités. */
    material: Material,

    /** La quantité actuelle. */
    quantity: number,
};

type Data = {
    bouncedQuantity: number,
};

// @vue/component
const MaterialsSelectorListQuantity = defineComponent({
    name: 'MaterialsSelectorListQuantity',
    props: {
        material: {
            type: Object as PropType<Required<Props['material']>>,
            required: true,
        },
        quantity: {
            type: Number as PropType<Required<Props['quantity']>>,
            required: true,
        },
    },
    emits: ['change'],
    data(): Data {
        return {
            bouncedQuantity: this.quantity,
        };
    },
    watch: {
        quantity(newValue: number) {
            this.bouncedQuantity = newValue;
        },
    },
    created() {
        this.updateQuantityDebounced = debounce(this.updateQuantity.bind(this), DEBOUNCE_WAIT);
    },
    beforeUnmount() {
        this.updateQuantityDebounced.cancel();
    },
    methods: {
        // ------------------------------------------------------
        // -
        // -    Handlers
        // -
        // ------------------------------------------------------

        handleChange(value: string) {
            this.bouncedQuantity = parseInt(value, 10) || 0;
            this.updateQuantityDebounced();
        },

        // ------------------------------------------------------
        // -
        // -    Méthodes internes
        // -
        // ------------------------------------------------------

        updateQuantity() {
            const { material, bouncedQuantity } = this;
            this.$emit('change', material, bouncedQuantity);
        },
    },
    render() {
        const { bouncedQuantity, handleChange } = this;

        return <QuantityInput value={bouncedQuantity} onChange={handleChange} />;
    },
});

export default MaterialsSelectorListQuantity;

// client/src/components/MaterialsListEditor/Quantity/index.tsx
import debounce from 'debounce';
import { toRefs, ref, watch } from '@vue/composition-api';
import QuantityInput from '@/components/QuantityInput';

import type { Render, SetupContext } from '@vue/composition-api';
import type { Material } from '@/stores/api/materials';

type Props = {
    material: Material,
    initialQuantity: number,
    onChange(material: Material, newQuantity: number): void,
};

// @vue/component
const MaterialsListEditorQuantity = (props: Props, { emit }: SetupContext): Render => {
    const { material, initialQuantity } = toRefs(props);

    const quantity = ref<number>(initialQuantity.value);

    const updateQuantityDebounced = debounce(() => {
        emit('change', material.value, quantity.value);
    }, 400);

    const handleChange = (value: string): void => {
        quantity.value = parseInt(value, 10) || 0;
        updateQuantityDebounced();
    };

    watch(initialQuantity, (newValue: number) => {
        quantity.value = newValue;
    });

    return () => (
        <QuantityInput value={quantity.value} onChange={handleChange} />
    );
};

MaterialsListEditorQuantity.props = {
    material: { type: Object, required: true },
    initialQuantity: { type: Number, default: 0 },
};

MaterialsListEditorQuantity.emits = ['change'];

export default MaterialsListEditorQuantity;
